import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from './_sections/Navbar/Navbar';
import { BebasNeue } from './fonts';
import { Toaster } from 'react-hot-toast';
import SchrollUp from '@/components/shared/ScrollUp';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Pascal is coding - Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="scroll-smooth" lang="en">
      <body className={`${BebasNeue.variable}`}>
        <Navbar />
        <SchrollUp />
        {children}
        <Toaster position="bottom-right" />
      </body>
    </html>
  );
}
